---

- hosts: all
  become: true
  remote_user:  ubuntu
  tasks:

    - name: update repository index
      shell: whoami
      register: cmd_output
    - name: View var
      debug:
        var: cmd_output
        #update_cache: yes

    - name: update repository index
      package:
        update_cache: yes
        

    - name: install apache2 package
      package:
        name: apache2
        state: absent

    - name: add php support for apache
      package:
        name: libapache2-mod-php
        state: absent
