---

- hosts: all
	become: true
  tasks:

	- name: update repository index
	  apt:
	    update_cache: yes
    when: ansible_distribution == "Ubuntu"

	- name: installing apache2 and php packages in a single module
	  apt:
	    name:
        - apache2
        - libapache2-mod-php
	    state: latest
    when: ansible_distribution == "Ubuntu"



  - name: update repository index
      dnf:
        update_cache: yes
    when: ansible_distribution_version == "CentOS"

  - name: install webserver package on CentOS Machine
      dnf:
        name:
          - httpd
          - php
        state: latest
    when: ansible_distribution == "CentOS"
