---

- hosts: web_servers
  become: true
  remote_user:  ubuntu
  tasks:

    - name:  update repository index
        apt:
	        update_cache: yes
      when:  ansible_distribution == "Ubuntu"

    - name: install apache2 package
	      apt:
	        name: apache2
	        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: add php support for apache
	      apt:
	        name: libapache2-mod-php
	        state: latest
      when: ansible_distribution == "Ubuntu"
 

    - name: update repository index
        package:
          update_cache: yes
      when: ansible_distribution_version == "fedora"

    - name: install webserver package on CentOS Machine
        package:
          name: httpd
          state: latest
      when: ansible_distribution == "fedora"

    - name: add php support for webserver-httpd on CentOS Machine
        package:
          name: php
          state: latest
      when: ansible_distribution == "fedora"
